FROM node:12.18.4 as build-stage
WORKDIR /app
RUN npm install -g @angular/cli@11.0.6
COPY movie-frontend/package*.json ./
RUN npm install
COPY movie-frontend/ .
RUN npm run build -- --prod --output-path=dist/movie-frontend
FROM nginx:1.19-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-stage /app/dist/movie-frontend /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]