apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
        - name: movie-frontend-container
          image: rahindev/movie-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          readinessProbe:
            httpGet:
              path: /
              port: 4200
            initialDelaySeconds: 5
            periodSeconds: 10
