apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakila-db
  namespace: movie-application
  labels:
    app: sakila-db-app
spec:
  selector:
    matchLabels:
      app: sakila-db-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sakila-db-app
        tier: mysql
    spec:
      containers:
        - image: rahindev/sakila-db:latest
          name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-database-name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-user-password
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
