apiVersion: v1
kind: Service
metadata:
  name: sakila-db
  labels:
    app: sakila-db-app
spec:
  type: LoadBalancer  # Changed to LoadBalancer for external access
  selector:
    app: sakila-db-app
    tier: mysql
  ports:
    - protocol: TCP
      name: mysql
      port: 3306
      targetPort: 3306
