apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service-container
          image: rahindev/movie-service:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-deployment:3306/sakila?user=root&password=root&useUnicode=true&characterEncoding=UTF-8
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: movie-service-service
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
