apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend-service
  namespace: movie-application
  labels:
    app: movie-backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-backend-service
  template:
    metadata:
      labels:
        app: movie-backend-service
    spec:
      containers:
        - name: movie-backend-service
          image: rahindev/movie-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-user-password
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-user-username
